Feature pack#5
Solovey42/LocalizationHelper pull request #2
Opened 2020-11-10 14:59 UTC by Solovey42

2020-11-11 17:47 UTC, chrnsv requested changes

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/Update.swift
> +    func run(languages: inout [Language], word: String, key: String, language: String, updatingDataClass: SetDataProtocol, getterStrings: GetStringKeysProtocol) throws {
Ух

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/Update.swift
>              exit(0)
Класс, отвечающий только за обновление данных еще и что-то выводит и завершает программу, давай так не делать

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/Update.swift
> +    func run(languages: inout [Language], word: String, key: String, language: String, updatingDataClass: SetDataProtocol, getterStrings: GetStringKeysProtocol) throws {
Получается какая-то статическая функция, спрятанная в класс, давай все-таки сервисы сделаем зависимостями класса

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/main.swift
> +var data = try getterData.gettingData()
Данные получились какой-то супер глобальной зависимостью

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/main.swift
> +if case .search(let key, let language) = arguments {
Обычно, делаем полный перебор значений енама через свитч

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/Search.swift
> +        if language == "" && key == "" {
А чем `""`  лучше `nil`?)

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/Search.swift
> +                    print("\t\(languages[n].key) = \(value)")
В одном месте и ищем и печатаем, давай разделим

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/main.swift
> +var data = try getterData.gettingData()
При этом получаешь ты их на уровне «контроллера», а сохраняешь на уровне «бизнес-логики»

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/SettingData/JsonSetter.swift
> +        try json.write(to: URL(fileURLWithPath: path))
Я медленно

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/Update.swift
> +                try updatingDataClass.settingData(languages: &languages)
выкидываю ошибку

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/main.swift
> +    try container.update.run(languages: &data,word: word, key: key, language: language, updatingDataClass: setterData, getterStrings: getterStrings)
Все выше и выше

2020-11-11 17:47 UTC, chrnsv commented on Sources/LocalizationHelper/main.swift
> +    try container.update.run(languages: &data,word: word, key: key, language: language, updatingDataClass: setterData, getterStrings: getterStrings)
И нигде ее не обрабатываю

2020-11-13 17:47 UTC, Solovey42 commented on Sources/LocalizationHelper/Search.swift
> +        if language == "" && key == "" {
Тем что потом в коде есть вот такие проверки [](https://github.com/Solovey42/LocalizationHelper/pull/2/commits/36294bea0fa43c36bb409caa4a151bfaba9b7a27#diff-e52021e64c10f763a3614fde00bf9c1d04a8dba7030cda99e529646c8fa83e04R105l)

2020-11-14 15:36 UTC, chrnsv requested changes

2020-11-14 15:36 UTC, chrnsv commented on Sources/LocalizationHelper/Parsing/ArgumentParser.swift
> +                print(Arguments.helpMessage())
Печатать сразу в паркинге не очень хорошо, лучше сделать возможность получить сообщение о помощи, а печатать его уже централизованно в одном месте с остальными данными

2020-11-14 15:36 UTC, chrnsv commented on Sources/LocalizationHelper/SearchingProtocol.swift
> +    var updaterClass: UpdatingProtocol? { get set }
А зачем эти зависимости в протоколе?

2020-11-14 15:36 UTC, chrnsv commented on Sources/LocalizationHelper/SearchingProtocol.swift
> +    func run(command: String,key: String, language: String, word:String, gettingDataClass: GetDataProtocol, updatingDataClass: SetDataProtocol, getterStrings: GetStringKeysProtocol, deleterClass:Dele
Почему эта почти статическая функция, которая принимает команду находится в классе, который, судя по названию, должен отвечать за поиск слов?

2020-11-14 15:36 UTC, chrnsv commented on Sources/LocalizationHelper/main.swift
> +    try searcher.run(command: command, key: key ?? "", language: language ?? "", word: "", gettingDataClass: getterData, updatingDataClass: setterData, getterStrings: getterStrings, deleterClass: del
Три раза одна и та же функция, а зачем тогда свитч?)

2020-11-14 15:36 UTC, chrnsv commented on Sources/LocalizationHelper/main.swift
> +default: break
А зачем?

2020-11-14 15:40 UTC, chrnsv requested changes

2020-11-14 15:40 UTC, chrnsv commented on Sources/LocalizationHelper/Search.swift
> +    func searchWitAllArg(word: String, key: String, language: String, languagesKeys: [String], languages: inout [Language]) {
вот тут написано поиск со всеми аргументами

2020-11-14 15:40 UTC, chrnsv commented on Sources/LocalizationHelper/Search.swift
> +                        deleterClass?.deleteWithAllArg(indexValue: i, key: key, languages: &languages)
А тут, внезапно, удаление

2020-11-14 15:40 UTC, chrnsv commented on Sources/LocalizationHelper/Search.swift
> +                        updaterClass?.update(indexValue: i, word: word, key: key, languages: &languages)
И тут обновление

2020-11-14 15:40 UTC, chrnsv commented on Sources/LocalizationHelper/Search.swift
> +                        print("\t\(languages[i].key): \(value)")
В одном классе и ищем и печатаем (а еще решаем нужно ли удалить/обновить), какой-то монстр-класс получился

2020-11-24 13:44 UTC, chrnsv approved these changes

2020-11-24 13:44 UTC, chrnsv commented on Sources/LocalizationHelper/Delete.swift
> +        self.searchCLass = searchingClass
`CLass`

2020-11-24 13:44 UTC, chrnsv commented on Sources/LocalizationHelper/Delete.swift
> +                let argLanguage = language {
Кодстайл

2020-11-24 13:44 UTC, chrnsv commented on Sources/LocalizationHelper/Delete.swift
> +        self.languages = try gettingDataClass.gettingData()
А зачем тут сохранять в параметры класса?

2020-11-24 13:44 UTC, chrnsv commented on Sources/LocalizationHelper/SearchingProtocol.swift
> +    var outputClass: OutputProtocol { get set }
А зачем тут?

2020-11-24 13:44 UTC, chrnsv commented on Sources/LocalizationHelper/Show.swift
> +    var languages: [Language] = []
Тот же вопрос про сохранение в переменные класса

2020-11-24 13:44 UTC, chrnsv commented on Sources/LocalizationHelper/main.swift
> +    try show.startShowing(key: key ?? nil, language: language ?? nil)
А зачем `?? nil` Будет работать как `nil` или `nil`

2020-11-24 15:29 UTC, merged